"""nuemiau email

Revision ID: 1f499c84d670
Revises: 2033b4548199
Create Date: 2025-03-24 21:01:55.974611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f499c84d670'
down_revision = '2033b4548199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_confirmed')
        batch_op.drop_column('confirmed_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_on', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_confirmed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
